### ISSUE TITLE
No titles are shown

### ISSUE THREAD

**Issue by davehakkens** [hakkens/story-hopper#22] opened 2015-12-08 12:41 UTC
Often de title ' stories worth sharing' and 'the stories' aren't shown on my macbook (chrome)
Not sure why.. 

<img width="1532" alt="schermafbeelding 2015-12-07 om 21 31 06" src="https://cloud.githubusercontent.com/assets/13672737/11655811/fa37767c-9db0-11e5-993c-bc735c8af719.png">

**Comment by leo** [comment] 2015-12-08 18:01
Hmm. I'm currently not able to reproduce this issue. Could you please open the dev tools and upload a screenshot (so that the console is visible, too) :blush:

**Comment by davehakkens** [comment] 2015-12-08 18:52
<img width="1920" alt="schermafbeelding 2015-12-08 om 19 39 41" src="https://cloud.githubusercontent.com/assets/13672737/11664739/a8acc45a-9de3-11e5-974f-9151a5aa3fa3.png">
<img width="1919" alt="schermafbeelding 2015-12-08 om 19 40 11" src="https://cloud.githubusercontent.com/assets/13672737/11664740/a8aeb058-9de3-11e5-9142-6c7d7f844a9b.png">

**Comment by leo** [comment] 2015-12-08 19:08
Can you also show what's happening in the console? There seem to be some errors.

**Comment by leo** [comment] 2015-12-19 15:47
Can you also show what's happening in the console? There seem to be some errors.

**Comment by davehakkens** [comment] 2015-12-20 13:17
![image](https://cloud.githubusercontent.com/assets/13672737/11918117/499136fa-a724-11e5-860a-01806d8cbb9e.png)

**Comment by leo** [comment] 2015-12-20 15:08
Hmm, doesn't seem to be related to the subtitle now showing up. Did you already try clearing the cache and reloading? Because I'm not able to reproduce this error.

**Comment by davehakkens** [comment] 2015-12-29 20:48
Still have it every now and then.. Cache deleted. Version 47.0.2526.106 (64-bit)
It seems that the console says something about the .svg this time

![image](https://cloud.githubusercontent.com/assets/13672737/12041891/dd29b8f8-ae75-11e5-84be-0c3b45c278d8.png)

**Comment by leo** [comment] 2015-12-29 21:56
Thanks for the info! But the warning containing the term "SVG" isn't related to the problem in any way. The script containing the error also isn't part of the site (probably from YouTube).

Since I'm not able to reproduce this, I think this could have something todo with your extensions (turn them all of to see if it's working). All in all, I don't think this is a real, existing problem. And since we're not able to reproduce it, I guess we should close this issue now... :innocent:

**Comment by davehakkens** [comment] 2016-01-02 18:03
allright!

**Comment by davehakkens** [comment] 2016-01-08 16:30
Different computer, in Safari. 
![image](https://cloud.githubusercontent.com/assets/13672737/12203095/780d9aa6-b62d-11e5-95bc-5de07bb176f6.png)

**Comment by leo** [comment] 2016-01-08 20:05
No errors shown in the console. Maybe it's because it's an old version... Which one is it?

**Comment by davehakkens** [comment] 2016-01-09 15:59
Versie 8.0.5 (10600.5.17)
Old-er, not super old  



Op vrijdag 8 januari 2016, om 21:05 heeft Leonard Lamprecht het volgende geschreven:

**Comment by leo** [comment] 2016-03-29 22:21
Closing this now, since I'm not able to reproduce it on any of my testing systems. Might revisit it as soon as the site will be converted into a static one (will probably fix it automatically).

**Closed by leo** 2016-03-29 22:21 UTC
Labels: invalid
